config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to:'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' =>'relationships#followers', as: 'followers'
  end 
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  post 'follow/:id' => 'relationship#follow', as: 'follow'
  post 'unfollow/:id' => 'relationship#unfollow', as: 'unfollow'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  # ユーザーをフォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしていれば、trueを返す
  def following?(user)
    followings.include?(user)
  end


  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all
      render :index
    end

  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end


  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if  @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book_show = Book.find(params[:id])
    @book_show.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end 
  
  def about
  end 
  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = @book.id
    comment.save
    @post_comment = PostComment.new
  end

  def destroy
    PostComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
    @post_comment = PostComment.new
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end 
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end 
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @dates = search_for(@how, @model, @value)
  end 
  
  private
  
  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end 
  end 
  
  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end 
  end 
  
  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end 
  end 
  
  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end 
  end 
  
  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end 
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @users = User.all

  end
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <div class="container px-5 px-sm-0">
    <div class="error-text">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>

        <table class="table">
          <tbody>
            <tr>
            	<th>name</th>
            	<th><%= user.name %></th>
            </tr>
            <tr>
            	<th>introduction</th>
            	<th><%= user.introduction %></th>
            </tr>
            <tr>
            	<th>follows</th>
            	<th><%= link_to user_followings_path(user.id) do %>
            	      <%= user.followings.count %>
            	    <% end %>
            	</th>
            </tr>
            <tr>
            	<th>followers</th>
            	<th><%= link_to user_followers_path(user.id) do %>
            	      <%= user.followers.count %>
            	    <% end %>
            	</th>
            </tr>
          </tbody>
        </table>

        <div class="row">
          <% if current_user.id == user.id %>
            <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          <% else %>
            <% if current_user.following?(user) %>
              <td><%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-info" %></td>
            <% else %>
              <td><%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: "btn btn-success" %></td>
            <% end %>
          <% end %>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: book, local:true do |f| %>
          <div class="form-group">
            <p>Title</p>
            <%= f.text_field :title, class: "form-control book_title" %>
          </div>
          <div class="form-group">
            <p>Opinion</p>
            <%= f.text_area :body, class: "form-control book_body" %>
          </div>

          <div class="form-group">
            <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
        <% end %>
      </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<div class="error-text">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
  		<%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <h4 for="book_title">Title</h4>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <h4 for="book_opinion">Opinion</h4>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
  		<%= link_to 'Show', book_path(@book.id) %> |
  		<%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
  <%= render 'books/list', user: @user, book: @book %>
      <div class="col-md-8 offset-md-1">
         <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                    <% end %>
                </td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
                <td id="favorite-btn_<%= book.id %>"><%= render 'favorites/favorite-btn', book: book %></td>
                <td>コメント数：<%= book.post_comments.count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
</main>

app/views/books/show.html.erb
<main>
  <%= render 'books/list', user: @user, book: @book_new %>
      <div class="col-md-8 offset-md-1">
    		<h2>Book detail</h2>
    		<table class="table">
    		  <tbody>
      		    <tr>
                <td><%= attachment_image_tag @user, :profile_image, :fill, 40,40, format: 'jpeg', fallback: 'no_image.jpg', size: "40x40" %></br>
                    <%= link_to @book.user.name, user_path(@user.id) %></td>
                <td><%= link_to @book.title, book_path(@book.id) %></td>
                <td><%= @book.body %></td>
                <td id="favorite-btn_<%= @book.id%>"><%= render 'favorites/favorite-btn', book: @book %></td>
                <td id="comment-count"><%= render 'post_comments/comment-count', book: @book %></td>
                <% if @book.user == current_user %>
                  <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
                  <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %></td>
                <% end %>
              </tr>
          </tbody>
        </table>
        <div id="comment">
          <%= render 'post_comments/comment', book: @book, post_comment: @post_comment %>
        </div>
    </div>
  </div>
</main>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      ️<span class="text-danger">
          ❤<%= book.favorites.count %>
      </span>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <span class="text-primary">
        💙<%= book.favorites.count %>
      </span>
    <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/post_comments/_comment-count.html.erb
コメント数：<%= book.post_comments.count %>

app/views/post_comments/_comment.html.erb
<% book.post_comments.each do |post_comment| %>
  <div class="comments">
    <td>
      <%=attachment_image_tag post_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpg', size: "40x40" %>
      <%= post_comment.comment %>
      <% if post_comment.user == current_user %>
        <%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
      <% end %></br>
      <%= link_to post_comment.user.name, user_path(post_comment.user) %>
    </td>
  </div>
<% end %>
<div class="new-comment">
  <%= form_with(model:[book, post_comment], remote: true) do |f| %>
    <%= f.text_area :comment, row:'5', size: "90x5" %></br>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/post_comments/create.js.erb
$("#comment").html("<%= j(render 'post_comments/comment', book: @book, post_comment: @post_comment) %>");
$("text_area").val('')
$("#comment-count").html("<%= j(render 'post_comments/comment-count', book: @book) %>");

app/views/post_comments/destroy.js.erb
$("#comment").html("<%= j(render 'post_comments/comment', book: @book, post_comment: @post_comment) %>");
$("text_area").val('')
$("#comment-count").html("<%= j(render 'post_comments/comment-count', book: @book) %>");

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.relationships.count %></td>
          <td>フォロワー数：<%= user.reverse_of_relationships.count %></td>
          <td><%= link_to 'Show', user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.relationships.count %></td>
          <td>フォロワー数：<%= user.reverse_of_relationships.count %></td>
          <td><%= link_to 'Show', user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/search/search.html.erb
<div>
  <div>
    <% if @model == "user" %>
      <h2>Users search for '<%= @value %>'</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Introduction</th>
          </tr>
        </thead>
        <% @dates.each do |user| %>
          <tbody>
            <tr>
              <th><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></th>
              <th><%= user.name %></th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% elsif @model == "book" %>
      <h2>Books search for '<%= @value %>'</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @dates.each do |book| %>
          <tbody>
            <tr>
              <th><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></th>
              <th><%= book.title %></th>
              <th><%= book.body %></th>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% end %>
  </div>
</div>